const GET_PAGES = 'GET_PAGES'
const PAGINATE_PAGES = 'PAGINATE_PAGES'
const CREATE_PAGE = 'CREATE_PAGE'
const DELETE_PAGE = 'DELETE_PAGE'
const UPDATE_PAGE = 'UPDATE_PAGE'

export default { GET_PAGES, PAGINATE_PAGES, CREATE_PAGE, DELETE_PAGE, UPDATE_PAGE }
