const GET_ROLES = 'GET_ROLES'
const CREATE_ROLE = 'CREATE_ROLE'
const DELETE_ROLE = 'DELETE_ROLE'
const UPDATE_ROLE = 'UPDATE_ROLE'

export default { GET_ROLES, CREATE_ROLE, DELETE_ROLE, UPDATE_ROLE }
