const ADD_TOAST = 'ADD_TOAST'
const SHIFT_TOAST = 'SHIFT_TOAST'
const DELETE_TOAST = 'DELETE_TOAST'
const CLEAR_TOASTS = 'CLEAR_TOASTS'

export default { ADD_TOAST, SHIFT_TOAST, DELETE_TOAST, CLEAR_TOASTS }
