const GET_USERS = 'GET_USERS'
const PAGINATE_USERS = 'PAGINATE_USERS'
const GET_USER = 'GET_USER'
const DELETE_USER = 'DELETE_USER'
const UPDATE_USER = 'UPDATE_USER'

export default { GET_USERS, PAGINATE_USERS, GET_USER, DELETE_USER, UPDATE_USER }
